prefix rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
prefix xsd: <http://www.w3.org/2001/XMLSchema#>
prefix kgs: <http://www.bbn.com/ontologies/rush/knowledge-gain-system#>
prefix abox: <http://www.bbn.com/abox/rush/decomposer#>

SELECT DISTINCT 
    ?uuid ?producer_uuid ?original_producer_uuid 
    ?lineage_key ?lineage_parents 
    ?alert_type ?title ?score ?classification
    ?alert_start_date ?alert_end_date ?alert_create_date
    ?triple ?subject ?verb ?object ?confidence 
    ?location ?lat ?lon ?location_covariance
    ?velocity ?velocity_lon ?velocity_lat
    ?confidence
    ?object_uuid

    ?triple ?subject ?verb ?object
    (GROUP_CONCAT(DISTINCT ?concat_subject_attribute; SEPARATOR=" ~~~~ ") AS ?subject_attributes)
    (GROUP_CONCAT(DISTINCT ?concat_object_attribute; SEPARATOR=" ~~~~ ") AS ?object_attributes)

    ?object_id ?object_id_priority ?object_id_label ?object_id_uuid ?object_id_obj
    (GROUP_CONCAT(DISTINCT(?concat_object_id_alias); SEPARATOR=" ~~~~ ") AS ?object_id_aliases)
    (GROUP_CONCAT(DISTINCT(?concat_object_id_attribute); SEPARATOR=" ~~~~ ") AS ?object_id_attributes)

    ?object_type ?object_type_priority ?object_type_label ?object_type_uuid
    (GROUP_CONCAT(DISTINCT(?concat_object_type_alias); SEPARATOR=" ~~~~ ") AS ?object_type_aliases)
    (GROUP_CONCAT(DISTINCT(?concat_object_type_attribute); SEPARATOR=" ~~~~ ") AS ?object_type_attributes)
WHERE {
    {
        SELECT DISTINCT ?uuid ?producer_uuid ?original_producer_uuid 
            ?lineage_key ?lineage_parents 
            ?alert_type ?title ?score ?classification
            ?alert_start_date ?alert_end_date ?alert_create_date
            ?triple ?subject ?verb ?object ?confidence 
            ?location ?lat ?lon ?location_covariance
            ?velocity ?velocity_lon ?velocity_lat
            ?object_uuid

            ?triple_obj
            ?object_id_obj
            ?object_type_obj
        WHERE {
            GRAPH abox:TestingGraph-0dfbaff5-9ff6-4092-993f-0615e0997e0d {
                ?entry a kgs:Evidence ;
                    kgs:alertUUID ?uuid ;
                    kgs:producerUUID ?producer_uuid ;
                    kgs:originalProducerUUID ?original_producer_uuid ;
                    kgs:objectUUID ?object_uuid ;
                    kgs:lineageKey ?lineage_key ;
                    kgs:lineageParents ?lineage_parents ;
                    kgs:alertType ?alert_type ;
                    kgs:title ?title ;
                    kgs:score ?score ;
                    kgs:classification ?classification ;
                    kgs:alertStartDate ?alert_start_date ;
                    kgs:alertEndDate ?alert_end_date ;
                    kgs:alertCreateDate ?alert_create_date ;
                    kgs:confidence ?confidence ;
                    kgs:location ?location ;
                    kgs:latitude ?lat ;
                    kgs:longitude ?lon ;
                    kgs:locationCovariance ?location_covariance ;
                    kgs:velocity ?velocity ;
                    kgs:velocityLongitude ?velocity_lon ;
                    kgs:velocityLatitude ?velocity_lat .

                OPTIONAL { ?entry kgs:Triple ?triple_obj . }
                OPTIONAL { ?entry kgs:ObjectID ?object_id_obj . }
                OPTIONAL { ?entry kgs:ObjectType ?object_type_obj . }
            }
        }
    }

    GRAPH abox:TestingGraph-0dfbaff5-9ff6-4092-993f-0615e0997e0d {

        ?triple_obj kgs:triple ?triple ;
                    kgs:subject ?subject ;
                    kgs:verb ?verb ;
                    kgs:object ?object .


        #?object_id_obj kgs:id ?object_id .
        #               kgs:priority ?object_id_priority ;
         #              kgs:label ?object_id_label ;
          #             kgs:uuid ?object_id_uuid .

        ?object_type_obj kgs:id ?object_type ;
                        kgs:priority ?object_type_priority ;
                        kgs:label ?object_type_label ;
                        kgs:uuid ?object_type_uuid .
  }
}
GROUP BY ?uuid ?producer_uuid ?original_producer_uuid 
    ?lineage_key ?lineage_parents 
    ?alert_type ?title ?score ?classification
    ?alert_start_date ?alert_end_date ?alert_create_date
    ?triple ?subject ?verb ?object ?confidence 
    ?location ?lat ?lon ?location_covariance
    ?velocity ?velocity_lon ?velocity_lat
    ?triple ?subject ?verb ?object
    ?object_id ?object_id_priority ?object_id_label ?object_id_uuid
    ?object_type ?object_type_priority ?object_type_label ?object_type_uuid
    ?object_uuid
    ?object_id_obj

