prefix foaf: <http://xmlns.com/foaf/0.1/>
prefix ex: <http://bbn.com/ami/ix/ce#>
prefix abox: <http://www.bbn.com/abox/rush/decomposer#>

SELECT ?person ?fname
WHERE {
    GRAPH abox:GraphInstance-1234 {
        ?person foaf:knows "Albert" ;
                ex:fname ?fname .
    }
}