from enum import Enum

class QueryTerm(Enum):
    RPAREN = ")"
    LPAREN = "("
    RBRACKET = "}"
    LBRACKET = "{"
    BASE = "BASE"
    PREFIX = "PREFIX"
    IRIREF = "FULLY_SPECIFIED_IRI"
    PREFIXED_NAME_PREFIX = "PREFIXED_NAME_PREFIX"
    PREFIXED_NAME_LOCAL = "PREFIXED_NAME_LOCAL"
    COLON = ":"
    IRI = "IRI"
    FROM = "FROM"
    SELECT = "SELECT"
    VARIABLE = "VARIABLE"
    WHERE = "WHERE"
    DISTINCT = "DISTINCT"
    AS = "AS"
    NAMED = "NAMED"
    GRAPH = "GRAPH"
    OPTIONAL = "OPTIONAL"
    EOF = "EOF"
